'use client';
import React,{useState} from 'react';
import {ProductComparisonView} from '@/components/product-comparison';
export function MarketReview(){
 const [narrow,setNarrow]=useState(false);
 const source={index:0,title:'Washable warm white paint · 2.5 L',url:'https://sample-store.example/products/paint',price:29.90,purchaseUnit:'pot',quantityPerPack:2.5,coveragePerUnit:25,note:'Synthetic layout fixture. No actual offer, stock or availability is claimed.'};
 const artifact:any={id:'synthetic-layout-only',data:{title:'Living room',country:'FR',city:'Mulhouse',currency:'EUR',items:[{item:'Wall paint',specification:'Washable warm white',basis:'manual',manualQuantity:5,unit:'litre',coveragePerUnit:null,coats:1,waste:0,priceLow:15,priceHigh:35}],assumptions:[],exclusions:[],productComparisons:{0:{products:[source,{...source,url:'https://second-store.example/products/paint',title:'Durable matt interior paint · 2.5 L',price:24.90},{...source,url:'https://third-store.example/products/paint',title:'Premium washable finish · 2.5 L',price:39.90},{...source,url:'https://fourth-store.example/products/paint',title:'Warm white eco finish · 2.5 L',price:32.50}],notice:'Synthetic data for layout review only.',checkedAt:'2026-10-08T08:00:00Z'}}}};
 return <main style={{background:'#eef2e8',padding:'24px',minHeight:'100vh',fontFamily:'Arial,sans-serif'}}><header style={{maxWidth:720,margin:'0 auto 20px'}}><h1>Product market · layout review</h1><p>Synthetic fixtures. No real retailer offers. Search and selection cannot write to a customer bill.</p><button onClick={()=>setNarrow(value=>!value)}>{narrow?'Show wide layout':'Show narrow panel'}</button></header><div className="chatKit" onClickCapture={e=>{if((e.target as Element).closest(".marketProductActions")){e.preventDefault();e.stopPropagation();}}} style={{display:'block',width:narrow?'360px':'min(100%,720px)',maxWidth:'100%',height:'auto',margin:'auto',background:'transparent'}}><ProductComparisonView artifact={artifact} index={0} onChanged={()=>{}} unlocked={false}/></div></main>;
}
