import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
import {SCHEMA} from '../lib/repository';
import {creditAccount,debitCredits,refundCredits,grantInvoiceCredits,requirePaid,CreditError} from '../lib/credits';
async function fixture(){const db=new PGlite();await db.exec(SCHEMA);const owner=randomUUID();await db.query('INSERT INTO roomwise.users(id,email,stripe_customer_id) VALUES($1,$2,$3)',[owner,'credits@test.com','cus_test']);return {db,owner};}
test('free credits are once per account, race-safe and cannot go negative',async()=>{const {db,owner}=await fixture();await Promise.all(Array.from({length:8},()=>creditAccount(db as any,owner)));assert.equal((await creditAccount(db as any,owner)).credits,10);await assert.rejects(()=>requirePaid(db as any,owner),CreditError);const results=await Promise.allSettled(Array.from({length:16},(_,i)=>debitCredits(db as any,owner,'message:'+i,'message')));assert.equal(results.filter(x=>x.status==='fulfilled').length,10);assert.equal((await creditAccount(db as any,owner)).credits,0);await db.close();});
test('message/image/search debit fixed amounts, repeat dispatch is idempotent and refunds once',async()=>{const {db,owner}=await fixture();await debitCredits(db as any,owner,'m','message');await debitCredits(db as any,owner,'i','image');await debitCredits(db as any,owner,'i','image');await debitCredits(db as any,owner,'s','search');assert.equal((await creditAccount(db as any,owner)).credits,3);await Promise.all(Array.from({length:5},()=>refundCredits(db as any,owner,'i')));assert.equal((await creditAccount(db as any,owner)).credits,5);await db.close();});
test('paid invoice is granted once across webhook/confirmation, rollover retained, wrong owner blocked',async()=>{const {db,owner}=await fixture();await creditAccount(db as any,owner);await Promise.all(Array.from({length:6},()=>grantInvoiceCredits(db as any,owner,'in_1','basic','sub_1','cus_test',100)));assert.equal((await creditAccount(db as any,owner)).credits,40);assert.equal((await requirePaid(db as any,owner)).plan,'basic');await debitCredits(db as any,owner,'search','search');await grantInvoiceCredits(db as any,owner,'in_2','basic','sub_1','cus_test',200);assert.equal((await creditAccount(db as any,owner)).credits,66);assert.equal(await grantInvoiceCredits(db as any,owner,'in_bad','pro','sub_2','cus_foreign',300),false);assert.equal((await creditAccount(db as any,owner)).credits,66);await db.close();});
test('Gmail aliases cannot claim the free allowance again, while paid invoice credits still work',async()=>{const {db,owner}=await fixture();const alias=randomUUID(),other=randomUUID();await db.query('UPDATE roomwise.users SET email=$1 WHERE id=$2',['person.name@gmail.com',owner]);await db.query('INSERT INTO roomwise.users(id,email,stripe_customer_id) VALUES($1,$2,$3),($4,$5,$6)',[alias,'personname+second@googlemail.com','cus_alias',other,'different@gmail.com','cus_other']);assert.equal((await creditAccount(db as any,owner)).credits,10);assert.equal((await creditAccount(db as any,alias)).credits,0);assert.equal((await creditAccount(db as any,other)).credits,10);await grantInvoiceCredits(db as any,alias,'in_alias','basic','sub_alias','cus_alias',300);assert.equal((await requirePaid(db as any,alias)).credits,30);await db.close();});
