"use client";
import { Button } from "@base-ui-components/react/button";
import { Camera,Sun,Moon,Sparkles,Box,Grid2X2,Eye } from "lucide-react";
import { MATERIALS,LIGHTING,applyFinish,roomAppearance,materialFor,type LightingId } from "@/lib/cad/appearance";
import type { RoomCad } from "@/lib/cad/model";
export function MaterialControls({model,selection,onSelect,onChange}:{model:RoomCad;selection:string;onSelect:(id:string)=>void;onChange:(model:RoomCad)=>void}){
 const target=selection==="floor"||model.fixtures.some(f=>f.id===selection)?selection:"walls",active=materialFor(model,target==="walls"?"wall-0":target);
 return <section className="cadCreativePanel" aria-label="Room materials"><h2>Find your finish.</h2><p>Try a texture, then make the colour yours. Changes appear in your room immediately.</p>
 <label className="cadSurfacePicker"><span>Apply to</span><select aria-label="Material surface" value={target} onChange={e=>onSelect(e.target.value==="walls"?"wall-0":e.target.value)}><option value="floor">Floor</option><option value="walls">Walls</option>{model.fixtures.map(f=><option key={f.id} value={f.id}>{f.label}</option>)}</select></label>
 <div className="cadMaterialGrid">{MATERIALS.map(m=><Button key={m.id} aria-pressed={active===m.id} onClick={()=>onChange(applyFinish(model,target,m.id))}><span className={`cadMaterialSample finish-${m.id}`} style={{backgroundColor:m.color}}/><strong>{m.name}</strong></Button>)}</div>
 <label className="cadTint"><span>Your colour</span><input aria-label="Material colour" type="color" value={target==="floor"?model.floorColor:target==="walls"?model.wallColor:model.fixtures.find(f=>f.id===target)!.color} onChange={e=>onChange(target==="floor"?{...model,floorColor:e.target.value}:target==="walls"?{...model,wallColor:e.target.value}:{...model,fixtures:model.fixtures.map(f=>f.id===target?{...f,color:e.target.value}:f)})}/></label>
 <h3>A little inspiration</h3><div className="cadMoodGrid">{[{name:"Quiet spa",floor:"stone" as const,wall:"paint" as const,color:"#eee8db"},{name:"Warm minimal",floor:"oak" as const,wall:"paint" as const,color:"#f2efe8"},{name:"Modern calm",floor:"concrete" as const,wall:"paint" as const,color:"#e2e5de"}].map(p=><Button key={p.name} onClick={()=>{const next=applyFinish(applyFinish(model,"floor",p.floor),"walls",p.wall);onChange({...next,wallColor:p.color});}}><span className={`cadMoodSwatch finish-${p.floor}`}/>{p.name}</Button>)}</div><p className="cadFinePrint">Finish previews are illustrative. Your room photos remain the reference for real textures.</p></section>;
}
export function LightingControls({model,onChange}:{model:RoomCad;onChange:(model:RoomCad)=>void}){
 const a=roomAppearance(model);function mood(id:LightingId){onChange({...model,appearance:{...a,lighting:id}});}
 return <section className="cadCreativePanel" aria-label="Room lighting"><h2>Set the atmosphere.</h2><p>See how your finishes feel at different times of day.</p><div className="cadLightingGrid">{LIGHTING.map(l=><Button key={l.id} aria-pressed={a.lighting===l.id} onClick={()=>mood(l.id)}><span className={`cadLightSample mood-${l.id}`}>{l.id==="evening"?<Moon size={22}/>:l.id==="studio"?<Sparkles size={22}/>:<Sun size={22}/>}</span><strong>{l.name}</strong><small>{l.description}</small></Button>)}</div><label className="cadBrightness"><span>Light level <small>{Math.round(a.brightness*100)}%</small></span><input aria-label="Light level" type="range" min=".4" max="1.6" step=".05" value={a.brightness} onChange={e=>onChange({...model,appearance:{...a,brightness:Number(e.target.value)}})}/></label><p className="cadFinePrint">A visual lighting study, rather than a simulation of installed fixtures.</p></section>;
}
export function ViewControls({active,onView,onSnapshot}:{active:string;onView:(view:string)=>void;onSnapshot:()=>void}){
 return <section className="cadCreativePanel" aria-label="Room views"><h2>A new perspective.</h2><p>Explore the layout, step inside, or keep a view to share.</p><div className="cadCameraGrid">{[{id:"iso",name:"Overview",icon:Box,description:"The whole room at a glance"},{id:"inside",name:"Inside",icon:Eye,description:"Look around at room level"},{id:"top",name:"Top",icon:Grid2X2,description:"A clear view of your layout"},{id:"front",name:"Front",icon:Camera,description:"See heights and proportions"}].map(v=><Button key={v.id} aria-pressed={active===v.id} onClick={()=>onView(v.id)}><v.icon size={24}/><strong>{v.name}</strong><small>{v.description}</small></Button>)}</div><Button className="cadSnapshot" onClick={onSnapshot}><Camera size={15}/>Save this view · PNG</Button><p className="cadFinePrint">Drag to look around. Scroll or pinch to move closer.</p></section>;
}
