"use client";
import {useEffect,useRef,useState} from 'react';
import { BrandMark } from "@/components/brand-mark";
import { track } from "@vercel/analytics";
import Link from 'next/link';
import {ArrowRight,Check,Sparkles,ArrowUpRight,Layers,Search,ListChecks} from 'lucide-react';
import {api} from '@/lib/browser-storage';
import {PLANS} from '@/lib/credits';
import './launch.css';
const faq=[['How do credits work?','A chat message uses 1 credit, a concept image uses 2, and a product search uses 4. Images and searches are additional to the message. Your balance and activity are visible in your workspace. Unused credits carry over; there are no manual resets.'],['What can I do for free?','Create an account to receive 10 credits once. Explore ideas, share room photos and generate concept previews. Bills of materials, construction plans and product research are included in Basic and Pro.'],['What does Basic include?','For $5/month, receive 30 credits each month after payment. Generate concepts, assess material quantities, create an exportable bill of materials and follow a linked construction plan.'],['Can I plan multiple projects?','Yes. All plans use the same private workspace. Pro includes 350 credits each month for professionals and people planning several rooms or projects.'],['Does the bill include real shopping links?','The default bill includes quantities and estimated allowances without a web search. Request research for a specific item to compare retailer products, verified links and published prices for your location.'],['Can I cancel?','Cancel in Settings → Plan & billing. Your saved projects remain accessible and unused credits stay in your account.'],['Can I build directly from the plan?','Archicova is a planning assistant. Photo-based dimensions and costs are estimates. Check measurements and specifications, and use qualified professionals for structural, electrical or plumbing work.']];
function Transformation(){
 const [before,setBefore]=useState(false);const scene=useRef<HTMLDivElement>(null);
 function move(e:React.PointerEvent<HTMLDivElement>){if(e.pointerType!=='mouse'||!scene.current)return;const b=scene.current.getBoundingClientRect();scene.current.style.setProperty('--window-x',Math.min(42,Math.max(6,(e.clientX-b.left)/b.width*100-26))+'%');scene.current.style.setProperty('--window-y',Math.min(34,Math.max(6,(e.clientY-b.top)/b.height*100-30))+'%');}
 return <div className="transformation" ref={scene} onPointerMove={move} onPointerLeave={()=>{scene.current?.style.setProperty('--window-x','24%');scene.current?.style.setProperty('--window-y','18%');}}>
  <img className="originalRoom" src="/images/living-before.webp" alt="Original living room with worn paint, traditional furniture and dark shelving" fetchPriority="high" width="1440" height="1080"/>
  {!before&&<><img className="renewedRoom" src="/images/living-after.webp" alt="The same living room reimagined with warm neutral finishes, modern furniture and lighting" width="1440" height="1080"/><div className="focusFrame"><span>YOUR NEXT CHAPTER</span><i/><i/><i/><i/></div></>}
  <div className="transformationTop"><span><Sparkles size={13}/> SAME ROOM. NEW POSSIBILITIES.</span><button onClick={()=>setBefore(!before)}>{before?'See the concept':'See before'}</button></div>
  <div className="transformationBottom"><span>{before?'01 / THE STARTING POINT':'02 / A CLEARER DIRECTION'}</span><small>Illustrative AI concept</small></div>
 </div>;
}
export default function Home(){
 const [signed,setSigned]=useState(false);useEffect(()=>{void api('/api/session').then(s=>setSigned(Boolean(s.user?.email))).catch(()=>{});},[]);
 return <main className="launchLanding">
 <header className="launchNav"><Link className="launchBrand" href="/"><BrandMark/>Archicova</Link><nav><a href="#possibilities">Possibilities</a><a href="#how">How it works</a><a href="#pricing">Plans</a><Link href="/en/guides/">Journal</Link></nav><Link className="launchSignIn" href={signed?'/chat':'/account?mode=login'}>{signed?'My workspace':'Sign in'}<ArrowUpRight size={15}/></Link></header>
 <section className="launchHero"><div className="launchHeroCopy"><p className="launchEyebrow"><span/> YOUR IDEA. A CLEARER DIRECTION.</p><h1>AI interior design.<br/><em>A real renovation plan.</em></h1><p>Turn room photos into interior design concepts, material lists and renovation cost estimates. Plan your next project with Archicova, from the first idea to the work ahead.</p><div className="launchActions"><Link className="launchPrimary" onClick={()=>track("signup_started",{source:"hero"})} href={signed?'/chat':'/account'}>Start creating for free <ArrowRight size={17}/></Link><a className="launchTextLink" href="#pricing">Find your plan <ArrowUpRight size={16}/></a></div><div className="launchTrust"><span>10 free credits</span><span>No card needed</span><span>Your own private workspace</span></div></div><Transformation/></section>
 <div className="launchTicker" aria-label="Archicova capabilities"><span>MODERNIZE</span><i>✦</i><span>REFURBISH</span><i>✦</i><span>VISUALIZE</span><i>✦</i><span>PLAN</span><i>✦</i><span>FIND YOUR FINISH</span></div>
 <section id="possibilities" className="launchSection"><p className="launchEyebrow">LESS GUESSWORK. MORE POSSIBILITY.</p><div className="launchSectionHeading"><h2>A fresh look.<br/><em>A practical next step.</em></h2><p>Modernize an outdated living room, refurbish your kitchen, refresh a bathroom or find furniture that ties it all together. Keep what works. Focus your effort where it makes a difference.</p></div><div className="launchFeatures"><article><Sparkles/><span>01 / IMAGINE</span><h3>See your space differently.</h3><p>Share a room photo. Explore renovation concepts that retain your room’s structure while bringing new materials, colours and lighting into focus.</p></article><article><Layers/><span>02 / SPECIFY</span><h3>Know what goes into it.</h3><p>Get a bill of materials with provisional quantities, tools, preparation supplies and estimated costs. Export your shopping list to Excel.</p></article><article><ListChecks/><span>03 / BUILD</span><h3>One connected work plan.</h3><p>Follow clear renovation steps linked to your materials. Check off completed work and keep everything in one organized project.</p></article><article><Search/><span>04 / FIND</span><h3>The right item for your idea.</h3><p>Request a focused product search. Compare retailer options, prices, pack sizes and shopping links suitable for your location.</p></article></div></section>
 <section id="how" className="launchProcess launchSection"><div><p className="launchEyebrow">FROM IDEA TO IMPLEMENTATION</p><h2>Your next project,<br/><em>all in one place.</em></h2></div><ol><li><b>01</b><div><h3>Bring your starting point.</h3><p>Upload a photo. Tell Archicova what you want to keep and what you want to change.</p></div></li><li><b>02</b><div><h3>Shape a direction you love.</h3><p>Talk through finishes and generate concepts. Compare them with your original room.</p></div></li><li><b>03</b><div><h3>Turn it into an actionable plan.</h3><p>Connect your visuals, material bill and work instructions. Consult your project when you shop or start work.</p></div></li></ol></section>
 <section id="journal" className="launchSection launchJournal"><div className="launchSectionHeading"><div><p className="launchEyebrow">THE ARCHICOVA JOURNAL</p><h2>Ideas worth reading.<br/><em>Projects worth making.</em></h2></div><p>Practical renovation advice, design inspiration and step-by-step guides. Find answers before you start, then bring your ideas into your Archicova workspace.</p></div><div className="launchJournalGrid"><Link href="/en/bathroom-renovation/" className="launchJournalCard"><img src="/inspiration/bathroom.jpg" alt="Bathroom renovation inspiration" loading="lazy"/><span>THE STARTING POINT</span><h3>Plan your bathroom renovation.</h3><p>From inspiration to materials and a workable plan.</p><small>Explore the guide <ArrowUpRight size={14}/></small></Link><Link href="/en/guides/small-bathroom-renovation-ideas/" className="launchJournalCard"><img src="/inspiration/bathroom2.jpg" alt="Bathroom layout and design ideas" loading="lazy"/><span>DESIGN IDEAS</span><h3>12 ideas for a smaller bathroom.</h3><p>Better storage, thoughtful finishes and more usable space.</p><small>Read the article <ArrowUpRight size={14}/></small></Link><Link href="/en/guides/bathroom-renovation-checklist/" className="launchJournalCard"><div className="launchJournalGraphic"><ListChecks size={44} strokeWidth={1.1}/></div><span>STEP-BY-STEP</span><h3>Start with the right checklist.</h3><p>Know what to measure, buy and confirm before work starts.</p><small>Read the checklist <ArrowUpRight size={14}/></small></Link></div><Link className="launchJournalAll" href="/en/guides/">Explore all renovation guides <ArrowRight size={16}/></Link></section>
 <section id="pricing" className="launchSection launchPricing"><p className="launchEyebrow">MAKE ROOM FOR YOUR NEXT IDEA</p><h2>A plan for <em>your ambition.</em></h2><div className="launchPlanGrid">{(['free','basic','pro'] as const).map(plan=><article key={plan} className={plan==='basic'?'featured':''}><div className="planTitle"><h3>{PLANS[plan].name}</h3>{plan==='basic'&&<span>FOR YOUR NEXT PROJECT</span>}</div><p className="planPrice">&#36;{PLANS[plan].monthly}<small>{plan==='free'?' / once':' / month'}</small></p><p className="planCredits">{PLANS[plan].credits} credits{plan!=='free'?' each month':''}</p><p>{plan==='free'?'Test an idea. Find a first direction.':plan==='basic'?'A focused project, from concept to work plan.':'For professionals and multiple projects.'}</p><ul>{(plan==='free'?['Room photo analysis','Concept previews','Saved chats and projects','10 credits once per account']:['Concept images and room assessment','Material bills & Excel export','Connected construction work plans','Optional product searches']).map(x=><li key={x}><Check size={15}/>{x}</li>)}</ul><Link className={plan==='basic'?'launchPrimary':'launchPlanButton'} onClick={()=>track("plan_selected",{plan,source:"pricing"})} href={plan==='free'?(signed?'/chat':'/account'):'/purchase?plan='+plan}>{plan==='free'?'Start for free':'Choose '+PLANS[plan].name}<ArrowRight size={16}/></Link></article>)}</div><p className="launchCreditNote">Message · 1 credit &nbsp; Concept image · 2 credits &nbsp; Product search · 4 credits<br/>Images and searches are additional to a message. Unused credits carry over. Cancel paid plans anytime.</p></section>
 <section className="launchSection launchFaq"><h2>A little more <em>clarity.</em></h2><div>{faq.map(([question,answer])=><details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>
 <section className="launchClosing"><p className="launchEyebrow">THE POTENTIAL IS ALREADY THERE.</p><h2>Let’s bring <em>it out.</em></h2><Link className="launchPrimary" onClick={()=>track("signup_started",{source:"footer"})} href={signed?'/chat':'/account'}>Create your first concept <ArrowRight size={17}/></Link></section>
 <footer className="launchFooter"><Link className="launchBrand" href="/"><BrandMark/>Archicova</Link><p>From idea to implementation.</p><Link href="/en/guides/">Renovation guides ↗</Link><small>Concepts and estimates require site verification.</small></footer>
 </main>;
}
