import Link from "next/link";
import Image from "next/image";
import type {ReactNode} from "react";
import "./editorial-bathroom.css";
import {PublicSiteHeader,PublicSiteFooter} from "@/components/public-site-chrome";
export const articles=[
{slug:"small-bathroom-renovation-ideas",title:"12 Small Bathroom Renovation Ideas That Actually Work",kind:"Inspiration",time:"9 min",desc:"Practical layout, storage, tile and lighting ideas for compact bathrooms."},
{slug:"best-bathroom-flooring",title:"Best Bathroom Flooring: Porcelain vs Vinyl vs Natural Stone",kind:"Materials",time:"11 min",desc:"Compare waterproofing, slip resistance, cost considerations and upkeep."},
{slug:"bathroom-renovation-cost",title:"Bathroom Renovation Cost: How to Budget Without Guesswork",kind:"Budget",time:"10 min",desc:"A transparent room-by-room budgeting method and cost drivers."},
{slug:"bathroom-renovation-checklist",title:"Bathroom Renovation Checklist: Plan Each Stage",kind:"Checklist",time:"8 min",desc:"A practical pre-renovation and handover checklist."},
{slug:"bathroom-renovation-step-by-step",title:"Bathroom Renovation: A Step-by-Step Planning Guide",kind:"How-to",time:"12 min",desc:"A realistic renovation sequence, decision gates and common mistakes."},
{slug:"best-small-bathroom-vanities",title:"Best Vanities for Small Bathrooms: What to Measure and Compare",kind:"Buying guide",time:"9 min",desc:"Sizing, storage and installation criteria before choosing a vanity."},
{slug:"walk-in-shower-vs-bathtub",title:"Walk-in Shower vs Bathtub: Which Makes Sense for Your Home?",kind:"Comparison",time:"9 min",desc:"Space, access, maintenance and work-scope trade-offs explained."}
];
export const guide=(slug:string)=>"/en/guides/"+slug+"/";
export const account="/account?next=%2Fchat";
export function EditorialLayout({children}:{children:ReactNode}){return <div className="edSite"><PublicSiteHeader/>{children}<PublicSiteFooter/></div>}
export function Hero({category,title,dek,image="/inspiration/bathroom.jpg",caption,children}:{category:string;title:string;dek:string;image?:string;caption?:string;children?:ReactNode}){return <header className="edHero"><div className="edHeroCopy"><div className="edKicker">{category} <span>•</span> ARCHICOVA JOURNAL</div><h1>{title}</h1><p>{dek}</p><div className="edMeta">Editorial guide <span>·</span> Updated October 2026 <span>·</span> Independent buying advice</div>{children}</div><figure className="edHeroImage"><Image src={image} alt={caption||"Bathroom design inspiration"} fill priority sizes="(max-width: 850px) 100vw, 50vw"/><figcaption>{caption||"Illustrative room inspiration. Not a verified completed project."}</figcaption></figure></header>}
export function Layout({children,side}:{children:ReactNode;side?:ReactNode}){return <div className="edContent"><article className="edArticle">{children}</article><aside className="edAside">{side||<Aside/>}</aside></div>}
export function Aside(){return <><div className="edAsideBox"><span className="edKicker">Make it yours</span><h3>Your room, your choices.</h3><p>Save inspiration and discuss designs, materials, products and work plans in the same Archicova chat.</p><Link href={account} className="edButton">Create an account ↗</Link><small>Free credits available after registration.</small></div><div className="edAsideBox edAsideLinks"><strong>Explore the bathroom vertical</strong><Link href="/en/bathroom-inspiration/">Bathroom inspiration ↗</Link><Link href="/en/ai-bathroom-design/">AI bathroom design ↗</Link><Link href="/en/bathroom-renovation/">Renovation overview ↗</Link></div></>}
export function TOC({items}:{items:{id:string;label:string}[]}){return <nav className="edTOC" aria-label="Table of contents"><span className="edKicker">In this guide</span><ol>{items.map(x=><li key={x.id}><a href={"#"+x.id}>{x.label}</a></li>)}</ol></nav>}
export function Section({id,title,children}:{id:string;title:string;children:ReactNode}){return <section id={id} className="edSection"><h2>{title}</h2>{children}</section>}
export function Figure({image="/inspiration/bathroom2.jpg",alt,caption}:{image?:string;alt:string;caption:string}){return <figure className="edFigure"><div><Image src={image} alt={alt} fill sizes="(max-width: 850px) 100vw, 760px"/></div><figcaption>{caption}</figcaption></figure>}
export function Callout({title,children,tone="neutral"}:{title:string;children:ReactNode;tone?:"neutral"|"warning"|"tip"}){return <aside className={"edCallout "+tone}><strong>{title}</strong><div>{children}</div></aside>}
export function ProductConsideration({category,why,check}:{category:string;why:string;check:string[]}){return <div className="edProduct"><span className="edKicker">SHOPPING DECISION</span><h3>{category}</h3><p>{why}</p><ul>{check.map(x=><li key={x}>{x}</li>)}</ul><p className="edFootnote">Product criteria only. No paid placement, unverified retailer price or affiliate recommendation.</p></div>}
export function Promo({title="See how your own bathroom could look",body="Create an account, bring your inspiration into chat and continue with material planning and product research."}:{title?:string;body?:string}){return <div className="edPromo"><span className="edKicker">FROM READING TO RENOVATING</span><h3>{title}</h3><p>{body}</p><Link href={account} className="edButton">Start in Archicova chat ↗</Link></div>}
export function Video({title,id,description}:{title:string;id:string;description:string}){return <div className="edVideo"><div className="edVideoFrame"><iframe src={"https://www.youtube-nocookie.com/embed/"+id} title={title} loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen/></div><p><strong>{title}.</strong> {description} <a href={"https://www.youtube.com/watch?v="+id} target="_blank" rel="noopener noreferrer">Watch on YouTube ↗</a></p><small>Independent third-party video. Its methods may not comply with local rules; inspect critically. Playing may share data with YouTube.</small></div>}
export function Table({headers,rows}:{headers:string[];rows:string[][]}){return <div className="edTableScroll"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div>}
export function Sources({items}:{items:{label:string;url:string}[]}){return <section className="edSources"><h2>Sources & further reading</h2><p>Links to primary guidance and independent demonstrations used in this article.</p><ul>{items.map(x=><li key={x.url}><a href={x.url} target="_blank" rel="noopener noreferrer">{x.label} ↗</a></li>)}</ul></section>}
export function Related({exclude}:{exclude:string}){return <section className="edRelated"><span className="edKicker">KEEP EXPLORING</span><h2>Read next</h2><div className="edRelatedGrid">{articles.filter(x=>x.slug!==exclude).slice(0,3).map(x=><Link href={guide(x.slug)} className="edRelatedCard" key={x.slug}><span>{x.kind} · {x.time}</span><strong>{x.title}</strong><p>{x.desc}</p><em>Read article ↗</em></Link>)}</div></section>}
export function ArticleStructured({title,description,path}:{title:string;description:string;path:string}){const data={"@context":"https://schema.org","@type":"Article",headline:title,description,datePublished:"2026-10-08",dateModified:"2026-10-08",inLanguage:"en",mainEntityOfPage:"https://archicova.com"+path,publisher:{"@type":"Organization",name:"Archicova",url:"https://archicova.com"}};return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data).replace(/</g,"\\u003c")}}/>}
