"use client";
import React,{useEffect,useState} from 'react';
import {Search,Check,ArrowRight,Palette} from 'lucide-react';
import {INSPIRATIONS,ROOM_TYPES} from '@/lib/inspiration-library';
import type {Artifact} from '@/lib/room-artifacts';
export function InspirationLibrary({artifact,onChanged,onRequest,saveSelection}:{artifact:Artifact;onChanged:()=>void|Promise<void>;onRequest?:(message:string)=>void;saveSelection?:(ids:string[],skipped:boolean)=>Promise<void>}){
 const [room,setRoom]=useState(artifact.data.room||'All'),[style,setStyle]=useState('All'),[query,setQuery]=useState(''),[ids,setIds]=useState<string[]>(artifact.data.selectedIds||[]),[confirmed,setConfirmed]=useState(!!artifact.data.confirmed),[saving,setSaving]=useState(false),[notice,setNotice]=useState('');
 const savedIds=JSON.stringify(artifact.data.selectedIds||[]);
 useEffect(()=>{setIds(JSON.parse(savedIds));setConfirmed(!!artifact.data.confirmed);setRoom(artifact.data.room||'All');},[artifact.id,savedIds,artifact.data.confirmed,artifact.data.room]);
 const references=INSPIRATIONS.filter(ref=>(room==='All'||ref.room===room)&&(style==='All'||ref.style===style)&&`${ref.title} ${ref.style} ${ref.room} ${ref.direction} ${ref.materials.join(' ')}`.toLowerCase().includes(query.toLowerCase()));
 async function save(skip=false){setSaving(true);setNotice('');try{if(saveSelection)await saveSelection(skip?[]:ids,skip);else{const response=await fetch(`/api/artifacts/${artifact.id}/inspiration`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:skip?[]:ids,skipped:skip})}),data=await response.json();if(!response.ok)throw Error(data.error);}if(skip)setIds([]);setConfirmed(true);await onChanged();}catch(error){setNotice(error instanceof Error?error.message:'Could not save references.');}finally{setSaving(false);}}
 function toggle(id:string){setIds(current=>current.includes(id)?current.filter(value=>value!==id):current.length<3?[...current,id]:current);}
 return <section className="inspirationLibrary" aria-label="Renovation inspiration library">
  <header><span><Palette size={14}/>FIND YOUR DIRECTION</span><h3>A room that feels like you.</h3><p>Explore our fixed collection. Choose up to three references; we’ll use the palette, materials and mood to guide your room design.</p><small>Browsing and saving are free · References show a style, not your actual room</small></header>
  {confirmed?<div className="inspirationSaved"><div className="inspirationChosen">{INSPIRATIONS.filter(ref=>ids.includes(ref.id)).map(ref=><figure key={ref.id}><img src={ref.image} alt={ref.title}/><figcaption>{ref.title}</figcaption></figure>)}</div><p><Check size={15}/>{ids.length?'Your direction is saved for this project.':'You’re starting with your own direction.'}</p><div className="inspirationFooter"><button onClick={()=>setConfirmed(false)}>Change references</button>{onRequest&&<button className="inspirationPrimary" onClick={()=>onRequest('Create a renovation design using my saved inspiration preferences. Preserve my actual room and retained elements. Ask me for a room photo if one is missing.')} disabled={saving}>Continue to design<ArrowRight size={14}/></button>}</div></div>:<>
   <div className="inspirationToolbar"><label><Search size={15}/><input aria-label="Search inspiration" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search styles, colours, materials…"/></label><select aria-label="Filter by style" value={style} onChange={event=>setStyle(event.target.value)}><option>All</option><option>Natural</option><option>Contemporary</option><option>Minimal</option></select></div>
   <nav aria-label="Inspiration room filters">{['All',...ROOM_TYPES].map(value=><button key={value} aria-pressed={room===value} onClick={()=>setRoom(value)}>{value}</button>)}</nav>
   <div className="inspirationGrid">{references.map(ref=>{const selected=ids.includes(ref.id);return <button key={ref.id} className={`inspirationCard ${selected?'selected':''}`} aria-pressed={selected} aria-label={`Select ${ref.title}, ${ref.room}`} disabled={saving||(!selected&&ids.length>=3)} onClick={()=>toggle(ref.id)}><div className="inspirationPhoto"><img src={ref.image} alt={`${ref.room} reference: ${ref.direction}`} loading="lazy"/>{selected&&<span className="inspirationTick"><Check size={14}/></span>}<small>{ref.room} · {ref.style}</small></div><div className="inspirationCaption"><strong>{ref.title}</strong><div className="inspirationPalette">{ref.palette.map(colour=><i key={colour} style={{background:colour}}/>)}<span>{ref.materials.slice(0,2).join(' · ')}</span></div></div></button>;})}</div>
   {!references.length&&<p>No references match this filter. Try another room or search term.</p>}
   <div className="inspirationFooter"><span>{ids.length} / 3 selected{ids.length===3?' · Remove one to change it':''}</span><button disabled={saving} onClick={()=>void save(true)}>Skip for now</button><button className="inspirationPrimary" disabled={saving||!ids.length} onClick={()=>void save()}>{saving?'Saving…':'Use these references'}<ArrowRight size={14}/></button></div>
  </>}
  {notice&&<p role="alert">{notice}</p>}<small className="inspirationCredit">Fixed reference photography from <a href="https://unsplash.com" target="_blank" rel="noopener noreferrer">Unsplash</a>. Selections are style guidance; feasibility depends on your room.</small>
 </section>;
}
