"use client";
import { useCallback,useEffect,useRef,useState } from "react";
import dynamic from "next/dynamic";
import { Button } from "@base-ui-components/react/button";
import { Box,Camera,FolderOpen,Image as ImageIcon,Layers,Plus,ShoppingBag,X } from "lucide-react";
import type { Artifact } from "@/lib/room-artifacts";
import { ProjectComparison } from "./project-comparison";
import { ProjectMaterials } from "./project-materials";
const CadStudio=dynamic(()=>import("./cad/studio").then(m=>m.CadStudio),{ssr:false});
export type ProjectHighlight={id:string;version:number}|null;
export type ProjectTab="visuals"|"materials"|"layout";
type Assets={artifacts:Artifact[];photos:{id:string;created_at:string}[];hasCad:boolean};
export function ProjectPanel({projectId,signal,focus,highlight,mobileOpen,busy,unlocked,onClose,onAsk,onDirtyChange,onArtifacts}:{projectId:string;signal:number;focus:ProjectTab;highlight:ProjectHighlight;mobileOpen:boolean;busy:boolean;unlocked:boolean;onClose:()=>void;onAsk:(text:string)=>void;onDirtyChange:(dirty:boolean)=>void;onArtifacts:(projectId:string,artifacts:Artifact[])=>void}){
 const [assets,setAssets]=useState<Assets>({artifacts:[],photos:[],hasCad:false}),[tab,setTab]=useState<ProjectTab>(focus),[compare,setCompare]=useState<Artifact|null>(null),[billId,setBillId]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[cadEditing,setCadEditing]=useState(false);
 const seenHighlight=useRef("");
 const attempted=useRef(new Set<string>()),dirty=useRef(false),mounted=useRef(true),request=useRef(0),controller=useRef<AbortController|null>(null);
 const load=useCallback(async()=>{const serial=++request.current;controller.current?.abort();const abort=new AbortController();controller.current=abort;try{const r=await fetch(`/api/projects/${projectId}/assets`,{signal:abort.signal}),data=await r.json();if(!r.ok)throw new Error(data.error);if(mounted.current&&serial===request.current){setAssets(data);setNotice("");}}catch(e){if(mounted.current&&!abort.signal.aborted)setNotice(e instanceof Error?e.message:"Could not load your project.");}finally{if(mounted.current&&serial===request.current)setLoading(false);}},[projectId]);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;controller.current?.abort();};},[]);
 useEffect(()=>{void load();},[load,signal]);
 useEffect(()=>{onArtifacts(projectId,assets.artifacts);},[projectId,assets.artifacts,onArtifacts]);
 useEffect(()=>{if(!dirty.current){setTab(focus);if(focus==="layout"&&assets.hasCad)setCadEditing(true);}},[focus,signal,assets.hasCad]);
 useEffect(()=>{if(!highlight)return;const key=`${highlight.id}:${highlight.version}`;if(seenHighlight.current===key)return;const a=assets.artifacts.find(a=>a.id===highlight.id);if(a&&!dirty.current){seenHighlight.current=key;if(a.kind==="estimate"){setTab("materials");setBillId(a.id);}else if(a.kind==="visual"){setTab("visuals");if(a.hasImage)setCompare(a);}else setTab("layout");}},[highlight,assets.artifacts]);
 const queued=assets.artifacts.filter(a=>a.kind==="visual"&&a.status==="queued"&&!a.hasImage);
 const pending=assets.artifacts.some(a=>a.kind==="visual"&&((a.status==="queued"&&unlocked)||a.status==="running")&&!a.hasImage);
 useEffect(()=>{if(!pending&&!busy)return;const timer=setInterval(()=>{if(document.visibilityState==="visible")void load();},5000);return()=>clearInterval(timer);},[pending,busy,load]);
 const generate=useCallback(async(id:string)=>{attempted.current.add(id);try{const r=await fetch(`/api/artifacts/${id}/image`,{method:"POST"}),data=await r.json();if(!r.ok&&r.status!==409)throw new Error(data.error);await load();}catch(e){if(mounted.current)setNotice(e instanceof Error?e.message:"The concept could not finish. Your design is saved.");}},[load]);
 useEffect(()=>{if(!unlocked)return;for(const a of queued)if(!attempted.current.has(a.id))void generate(a.id);},[assets,unlocked,generate]);
 function choose(next:ProjectTab){if(dirty.current){setNotice("Save or discard your layout edits before changing folders.");return;}setTab(next);}
 function ask(text:string){if(dirty.current){setNotice("Save or discard your layout edits before discussing them.");return;}onAsk(text);onClose();}
 const visuals=assets.artifacts.filter(a=>a.kind==="visual"),bills=assets.artifacts.filter(a=>a.kind==="estimate"),bill=bills.find(a=>a.id===billId)||bills[0];
 async function refreshPrices(){if(!bill)return;setRefreshing(true);try{const r=await fetch(`/api/artifacts/${bill.id}/prices`,{method:"POST"}),data=await r.json();if(!r.ok)throw new Error(data.error);await load();}catch(e){setNotice(e instanceof Error?e.message:"Could not refresh prices.");}finally{setRefreshing(false);}}
 return <aside id="roomwise-project" className={`projectPanel ${mobileOpen?"mobileOpen":""}`} aria-label="Your room project">
 <header className="projectPanelHead"><div><FolderOpen size={18}/><strong>Your project</strong></div><Button className="closeProjectPanel" aria-label="Close project panel" onClick={()=>{if(dirty.current){setNotice("Save or discard your layout changes first.");return;}onClose();}}><X size={18}/></Button></header>
 <nav className="projectFolders" aria-label="Project folders"><Button aria-pressed={tab==="visuals"} onClick={()=>choose("visuals")}><ImageIcon size={15}/>Visuals<span>{visuals.length}</span></Button><Button aria-pressed={tab==="materials"} onClick={()=>choose("materials")}><ShoppingBag size={15}/>Materials</Button><Button aria-pressed={tab==="layout"} onClick={()=>choose("layout")}><Layers size={15}/>Layout</Button></nav>
 {notice&&<div className="projectPanelNotice" role="status">{notice}<Button aria-label="Dismiss project message" onClick={()=>setNotice("")}><X size={12}/></Button></div>}
 {loading?<div className="projectBlank">Opening your project…</div>:tab==="visuals"?<div className="projectVisualFolder"><div className="projectSectionIntro"><small>YOUR DESIGN GALLERY</small><h2>See the possibilities.</h2><p>Original photos and room concepts, together in one place. Open a concept to compare.</p></div>
 {visuals.length?<div className="projectConceptGrid">{visuals.map(a=><article key={a.id} className="projectConcept"><Button className="conceptPreview" disabled={!a.hasImage} onClick={()=>setCompare(a)}><div className="conceptOriginal"><img src={`/api/photos/${a.data.sourcePhotoId}`} alt="Original room" loading="lazy"/><span>Before</span></div><div className="conceptAfter">{a.hasImage?<img src={`/api/artifacts/${a.id}/image`} alt={a.data.title} loading="lazy"/>:<div className={`conceptPending ${a.status==="running"?"animating":""}`}><Camera size={23}/><span>{a.status==="failed"?"Concept interrupted":!unlocked?"Room Pass required":a.status==="running"?"Creating your concept…":a.status==="queued"?"Preparing your concept…":"Saved design brief"}</span></div>}<span>After</span></div></Button><div className="conceptInfo"><div><h3>{a.data.title}</h3><small>{a.data.generationError&&!a.hasImage?a.data.generationError:a.hasImage?"Open to compare":a.status==="running"?"The finished image will appear here automatically.":"Your design brief is saved."}</small></div>{a.hasImage?<Button onClick={()=>setCompare(a)}>Compare</Button>:a.status==="failed"&&unlocked?<Button onClick={()=>void generate(a.id)}>Retry</Button>:!unlocked?<a href={`/purchase?plan=single&project=${projectId}`}>Room Pass</a>:null}</div></article>)}</div>:<div className="projectFolderEmpty"><Camera size={28}/><h3>Start with your room.</h3><p>Share a photo and describe the improvements you want. Your requested concept will appear here automatically.</p><Button onClick={()=>ask("Create a before/after refurbishment concept from my room photos. Keep the layout and retained features, and focus on finishes, lighting and furniture.")}><Plus size={14}/>Plan a visual</Button></div>}
 {!!assets.photos.length&&<section className="projectOriginals"><h3>Your original photos <span>{assets.photos.length}</span></h3><div>{assets.photos.map((p,i)=><a key={p.id} href={`/api/photos/${p.id}`} target="_blank" rel="noreferrer"><img src={`/api/photos/${p.id}`} alt={`Original room photo ${i+1}`} loading="lazy"/></a>)}</div></section>}
 {visuals.length>0&&<Button className="projectNewConcept" onClick={()=>ask("Create a new before/after concept from my original room photo, keeping the architecture. My updated style direction is: ")}><Plus size={14}/>Explore another direction</Button>}
 </div>:tab==="materials"?<div className="projectMaterialFolder"><div className="projectSectionIntro"><small>MATERIALS & SHOPPING</small><h2>Bring it together.</h2><p>Quantities, sourced prices and real provider links. Estimated allowances stay clearly marked.</p></div>{bills.length>1&&<label className="projectBillPicker">Saved bills<select aria-label="Select material bill" value={bill.id} onChange={e=>setBillId(e.target.value)}>{bills.map(a=><option key={a.id} value={a.id}>{a.data.title}</option>)}</select></label>}{bill?<ProjectMaterials artifact={bill} onAsk={ask} onRefresh={()=>void refreshPrices()} refreshing={refreshing}/>:<div className="projectFolderEmpty"><ShoppingBag size={28}/><h3>A clear shopping plan.</h3><p>Ask for a bill of materials using your chosen design, budget and location. Roomwise will research matching local products.</p><Button onClick={()=>ask("Build a bill of materials for my refurbishment with quantities, costs and verified local provider product links. Use my latest design and saved measurements. My shopping location is: ")}>Prepare my material bill</Button></div>}</div>:cadEditing?<CadStudio projectId={projectId} signal={signal} busy={busy} onAsk={ask} onClose={()=>{if(dirty.current){setNotice("Save or discard your layout changes first.");return;}setCadEditing(false);}} onDirtyChange={value=>{const wasDirty=dirty.current;dirty.current=value;onDirtyChange(value);if(wasDirty&&!value)void load();}}/>:<div className="projectLayoutFolder"><div className="projectSectionIntro"><small>LAYOUT & GEOMETRY</small><h2>Make space for change.</h2><p>Use the room studio for furniture placement, dimensions, openings or structural ideas.</p></div><div className="projectFolderEmpty"><Box size={32}/><h3>{assets.hasCad?"Your editable room model":"Plan the space when you need to."}</h3><p>Decorative refurbishment can stay in Visuals and Materials. Layout work has its own studio.</p><Button onClick={()=>setCadEditing(true)}>Open room studio</Button><Button onClick={()=>ask("Help me change the layout of my room. Create or update my editable CAD from my photos and retain the measurements I confirmed.")}>Discuss a layout change</Button></div></div>}
 {compare&&<ProjectComparison key={compare.id} artifact={compare} onClose={()=>setCompare(null)}/>}
 </aside>;
}
