"use client";
import React, {useEffect,useState} from 'react';
import {Button} from '@base-ui-components/react/button';
import {Download,ExternalLink,Check,ChevronDown,Search} from 'lucide-react';
import {materialPresentation,money,retailerName} from '@/lib/material-presentation';
import type {Artifact} from '@/lib/room-artifacts';
import {ProductComparisonView} from './product-comparison';
const categories=['preparation','finishes','furniture','tools','consumables'];
const labels:Record<string,string>={preparation:'Preparation & repairs',finishes:'Finishes & surfaces',furniture:'Furniture & fittings',tools:'Reusable tools',consumables:'Protection & consumables'};
function category(row:any){if(categories.includes(row.category))return row.category;if(/brush|roller|drill|tray|driver|level|detector|cutter|ladder|pole|brosse|pinceau|rouleau|perceuse/i.test(row.item))return 'tools';if(/tape|sheet|glove|mask|sandpaper|abrasive|ruban|bâche|gant/i.test(row.item))return 'consumables';if(/clean|primer|filler|repair|enduit|nettoy|sous.couche/i.test(row.item))return 'preparation';if(/shelf|handle|cabinet|vanity|furniture|light|shelv|étagère|meuble|poignée/i.test(row.item))return 'furniture';return 'finishes';}
export function ProjectMaterials({artifact,focusIndex,onChanged,unlocked,works=[],onStep}:{artifact:Artifact;works?:Artifact[];onStep?:(id:string,index:number)=>void;focusIndex?:number|null;onChanged:()=>void|Promise<void>;unlocked:boolean}){
 const [open,setOpen]=useState<number|null>(focusIndex??null),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false),[measureOpen,setMeasureOpen]=useState(false),[marketIndex,setMarketIndex]=useState<number|null>(null);
 const bill=materialPresentation(artifact),fmt=(n:number)=>money(n,bill.currency),range=(a:number,b:number)=>a===b?fmt(a):`${fmt(a)} – ${fmt(b)}`;
 useEffect(()=>{if(focusIndex!=null){setOpen(focusIndex);setTimeout(()=>document.getElementById(`material-${artifact.id}-${focusIndex}`)?.scrollIntoView({block:'nearest',behavior:'smooth'}),80);}},[focusIndex,artifact.id]);
 async function edit(body:unknown){setSaving(true);setNotice('');try{const r=await fetch(`/api/artifacts/${artifact.id}/project`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),result=await r.json();if(!r.ok)throw new Error(result.error);await onChanged();setMeasureOpen(false);}catch(e){setNotice(e instanceof Error?e.message:'Could not update your bill.');}finally{setSaving(false);}}
 useEffect(()=>{if(marketIndex!==null&&open===marketIndex)document.getElementById(`find-products-${artifact.id}-${marketIndex}`)?.scrollIntoView({block:"nearest",behavior:"smooth"});},[marketIndex,open,artifact.id]);
 const m=artifact.data.measurements;
 return <div className="projectMaterials"><div className="projectBudget"><small>PLANNED MATERIALS</small><strong>{range(bill.low,bill.high)}</strong><p>{[artifact.data.city,artifact.data.country].filter(Boolean).join(', ')} · {bill.rows.length} items · {Object.values(artifact.data.shoppingChecked||{}).filter(Boolean).length} ready</p><div><span>Selected products<b>{fmt(bill.sourced)}</b></span><span>Estimated allowances<b>{range(bill.allowanceLow,bill.allowanceHigh)}</b></span></div></div>
 <div className="projectBillActions"><a href={`/api/artifacts/${artifact.id}/export`}><Download size={14}/>Shopping list · Excel</a><Button onClick={()=>setMeasureOpen(!measureOpen)} aria-expanded={measureOpen}>Check quantities<ChevronDown size={13}/></Button></div>
 <p className="projectQuantityNote">{artifact.data.calculations?.provisional?'Provisional quantities — check the surfaces before ordering.':'Confirmed surface measurements.'} No product search runs until you request one.</p>
 {measureOpen&&<form className="projectMeasurements" key={JSON.stringify(m)} onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget),numbers=Object.fromEntries(['floorArea','wallArea','ceilingArea','perimeter'].map(key=>[key,form.get(key)?Number(form.get(key)):null]));void edit({action:'measurements',measurements:{...numbers,confirmed:form.get('confirmed')==='on',notes:String(form.get('notes')||'')}});}}><h3>Surfaces in your project</h3><p>Only include the areas you will finish. Subtract doors, windows and retained tiles from the walls.</p><div>{[['floorArea','Floor to cover · m²'],['wallArea','Walls to finish · m²'],['ceilingArea','Ceiling to finish · m²'],['perimeter','Skirting / edging · m']].map(([key,label])=><label key={key}>{label}<input name={key} type="number" min="0.01" max={key==='wallArea'?10000:key==='perimeter'?1000:1500} step="0.01" defaultValue={m?.[key]??''} placeholder="Not in scope"/></label>)}</div><label>Measurement notes<textarea name="notes" maxLength={1000} defaultValue={m?.notes||''} placeholder="Dimensions, deductions or estimated areas"/></label><label className="projectCheck"><input name="confirmed" type="checkbox" defaultChecked={!!m?.confirmed}/>I checked these measurements</label><Button type="submit" disabled={saving}>{saving?'Saving…':'Update quantities'}</Button></form>}
 {notice&&<p role="status" className="projectFootnote">{notice}</p>}
 <div className="projectMaterialGroups">{categories.map(group=>{const rows=bill.rows.filter((row:any)=>category(row)===group);if(!rows.length)return null;const low=rows.reduce((sum:number,row:any)=>sum+(row.subtotal??row.low),0),high=rows.reduce((sum:number,row:any)=>sum+(row.subtotal??row.high),0);return <details key={group} className="projectCompartment" open={open!==null&&rows.some((r:any)=>r.index===open)?true:undefined}><summary><span>{labels[group]}<small>{rows.length} items</small></span><b>{range(low,high)}</b><ChevronDown size={14}/></summary><div>{rows.map((row:any)=><article key={row.index} id={`material-${artifact.id}-${row.index}`} className={`materialLine ${open===row.index?'active':''}`}>
 <div className="materialLineHead"><Button className="shoppingCheck" aria-label={`Mark ${row.item} as ready`} aria-pressed={!!artifact.data.shoppingChecked?.[row.index]} disabled={saving} onClick={()=>void edit({action:'shopping',index:row.index,checked:!artifact.data.shoppingChecked?.[row.index]})}>{artifact.data.shoppingChecked?.[row.index]&&<Check size={12}/>}</Button><Button className="materialExpand" aria-expanded={open===row.index} onClick={()=>setOpen(open===row.index?null:row.index)}><span><strong>{row.item}</strong><small>{row.quantity} {row.unit} · {row.source?'Selected product':'Estimated allowance'}</small></span><b>{row.source?fmt(row.subtotal):range(row.low,row.high)}</b><ChevronDown size={13}/></Button><Button className="billFindProduct" aria-expanded={open===row.index} onClick={()=>{setOpen(row.index);setMarketIndex(row.index);}}><Search size={12}/>Find nearby products</Button></div>
 {open===row.index&&<div className="materialLineBody"><p>{row.specification}</p>{row.source&&<a className="productShop" href={row.source.url} target="_blank" rel="noopener noreferrer">{row.source.title} · {retailerName(row.source.url)}<ExternalLink size={13}/></a>}<div className="productFigures"><div><small>Basis</small><b>{row.base.toFixed(2)}{row.basis.includes('area')?' m²':row.basis==='perimeter'?' m':''}</b></div><div><small>Application</small><b>{row.coats} {row.coats===1?'coat':'coats'} · {Math.round(row.waste*100)}% waste</b></div><div><small>Buy</small><b>{row.quantity} {row.unit}</b></div></div><p className="projectQuantityNote">{row.base.toFixed(2)} × {row.coats} × {1+row.waste}{row.coveragePerUnit?` ÷ ${row.coveragePerUnit} coverage / ${row.unit}`:''}. Purchase packs round up; tools count once.</p><details className="rowQuantityEdit"><summary>Adjust this item's quantity basis</summary><form onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);void edit({action:'quantity',index:row.index,base:Number(form.get('base')),coats:Number(form.get('coats')),waste:Number(form.get('waste'))/100,coveragePerUnit:form.get('coverage')?Number(form.get('coverage')):null});}}><p>Use an item-specific quantity, such as cabinet area or number of fittings. It then stays independent of room-wide surface changes.</p><div>{[['base','Base quantity',row.base,.01,100000],['coats','Coats',row.coats,1,4],['waste','Waste %',row.waste*100,0,30],['coverage',`Coverage / ${artifact.data.quantityItems?.[row.index]?.unit||row.unit}`,artifact.data.quantityItems?.[row.index]?.coveragePerUnit??row.coveragePerUnit??'',.01,1000]].map(([key,label,value,min,max])=><label key={String(key)}>{label}<input name={String(key)} type="number" step={key==='coats'?'1':'0.01'} min={Number(min)} max={Number(max)} defaultValue={value} required={key!=='coverage'}/></label>)}</div><Button type="submit" disabled={saving}>Save item quantities</Button></form></details>{works.filter(work=>work.data.estimateId===artifact.id).slice(0,1).flatMap(work=>work.data.steps.map((step:any,index:number)=>step.materialIndexes.includes(row.index)?<Button className="materialWorkLink" key={`${work.id}-${index}`} onClick={()=>onStep?.(work.id,index)}>Used in: {step.title}</Button>:null))}<div id={`find-products-${artifact.id}-${row.index}`}><ProductComparisonView artifact={artifact} index={row.index} onChanged={onChanged} unlocked={unlocked}/></div></div>}
 </article>)}</div></details>;})}</div>
 {!!artifact.data.assumptions?.length&&<details className="projectExclusions"><summary>Quantity assumptions</summary>{artifact.data.assumptions.map((s:string,i:number)=><p key={i}>{s}</p>)}</details>}
 {!!artifact.data.exclusions?.length&&<details className="projectExclusions"><summary>Outside this materials budget</summary>{artifact.data.exclusions.map((s:string,i:number)=><p key={i}>{s}</p>)}</details>}
 </div>;
}
